config/routes.rb
Xcompany::Application.routes.draw do
  root :to => 'pages#home'

  match "/designers/all", :to => 'designers#all'
  match "/designers/awards", :to => 'designers#awards'
  match "/designers/show", :to => 'designers#show'
  match "/designers/new", :to => 'designers#new'
  match '/designers/:id' => 'designers#show'
  match "/designers/" => 'designers#create'

  resources :designers

  match "/products/new_home" => 'products#new_home'
  match 'products/new_office' => 'products#home_office'
  match "/products/all_home", :to => 'products#all_home'
  match "/products/all_office", :to => 'products#all_office'
  match "/products/by_partners", :to => 'products#by_partners'
  match '/products/office_by_type/:category' => 'products#office_by_type'
  match '/products/office_by_type' => 'products#office_by_type'
  match '/products/home_by_type/:category' => 'products#home_by_type'
  match '/products/home_by_type' => 'products#home_by_type'
  match 'products/products_retailers' => 'products#products_retailers'
  match 'products/show' => 'products#show'
  match 'products/top' => 'products#top'
  match '/products/:id' => 'products#show'
  match "/products/" => 'products#create'

  resources :products

  match "/events/by_date", :to => 'events#by_date'
  match 'events/by_region/', :to => 'events#by_region'
  match "/events/events_products", :to => 'events#events_products'
  match "/events/events_retailers", :to => 'events#events_retailers'
  match "/events/show", :to => 'events#show'
  match "/events/new", :to => 'events#new'
  match '/events/:id' => 'events#show'
  match "/events/" => 'events#create'

  resources :events

  match "/retailers/all", :to => 'retailers#all'
  match 'retailers/by_region/:region', :to => 'retailers#by_region'
  match "/retailers/regions", :to => 'retailers#regions'
  match "/retailers/retailers_products", :to => 'retailers#retailers_products'
  match "/retailers/show", :to => 'retailers#show'
  match "/retailers/where_we_are", :to => 'retailers#where_we_are'
  match "/retailers/new", :to => 'retailers#new'
  match '/retailers/:id' => 'retailers#show'
  match "/retailers/" => 'retailers#create'

  resources :retailers

  match "/admin" => 'pages#admin'
  get "pages/new_product_designer_relation"
  get "pages/new_product_retailer_relation"
  get "pages/new_product_event_relation"
  get "pages/new_retailer_event_relation"
  get "pages/home"
  get "pages/admin"
  get "pages/who_we_are"
  get "pages/where_we_are"
  get "pages/contact_us"
  get "pages/work_with_us"
  get "pages/partners"
  get "pages/services"

   match ':controller(/:action(/:id))(.:format)'
end

app/models/retailer.rb
class Retailer < ActiveRecord::Base
  attr_accessible :address, :description, :mail, :name, :phone_number, :photo_url, :region

  has_many :reverse_products_retailers_relationships, foreign_key: "retailer_id", class_name:  "ProductsRetailersRelationship", dependent:   :destroy
  has_many :products, through: :reverse_products_retailers_relationships, source: :product

  has_many :retailers_events_relationships, foreign_key: "retailer_id", dependent: :destroy
  has_many :events, through: :retailers_events_relationships, source: :event

  validates :name, :presence => true
  validates :address, :presence => true
  validates :description, :presence => true
  validates :mail, :presence => true
  validates :phone_number, :presence => true
  validates :region, :presence => true

end

app/controllers/retailers_controller.rb
class RetailersController < ApplicationController
  def by_region
    @retailers_by_region = Retailer.where('region = ?', params[:region])
    @reg = params[:region]
  end

  def all
    @all_retailers = Retailer.all
  end

  def show
    @retailer = Retailer.find(params[:id])

    @pro = params[:pro]
    @des = params[:des]
    @hom = params[:hom]
    @off = params[:off]
    @top = params[:top]
    @par = params[:par]
    @ret = params[:ret]
    @eve = params[:eve]
    @reg = params[:reg]
    @dat = params[:dat]
    @rall = params[:rall]

    if !@ret and !@rall and !@pro and !@eve
      @ret = @retailer.region
    end

    @path_left = case
                   when @pro
                     @r = Product.find(@pro).retailers
                     hash = Hash[@r.map.with_index.to_a]
                     @i = hash[@retailer]
                     @m = @r.count

                     (@i == 0 ? retailers_show_path(:id => @r[@m - 1].id, :pro => @pro, :des => @des, :hom => @hom, :off => @off, :top => @top, :par => @par, :ret => @ret, :eve => @eve, :reg => @reg, :dat => @dat, :rall => @rall) : retailers_show_path(:id => @r[@i.to_i - 1].id, :pro => @pro, :des => @des, :hom => @hom, :off => @off, :top => @top, :par => @par, :ret => @ret, :eve => @eve, :reg => @reg, :dat => @dat, :rall => @rall))
                   when @ret
                     @r = Retailer.where('region = ?', @ret)
                     hash = Hash[@r.map.with_index.to_a]
                     @i = hash[@retailer]
                     @m = @r.count

                     (@i == 0 ? retailers_show_path(:id => @r[@m - 1].id, :pro => @pro, :des => @des, :hom => @hom, :off => @off, :top => @top, :par => @par, :ret => @ret, :eve => @eve, :reg => @reg, :dat => @dat, :rall => @rall) : retailers_show_path(:id => @r[@i.to_i - 1].id, :pro => @pro, :des => @des, :hom => @hom, :off => @off, :top => @top, :par => @par, :ret => @ret, :eve => @eve, :reg => @reg, :dat => @dat, :rall => @rall))
                   when @eve
                     @r = Event.find(@eve).retailers
                     hash = Hash[@r.map.with_index.to_a]
                     @i = hash[@retailer]
                     @m = @r.count

                     (@i == 0 ? retailers_show_path(:id => @r[@m - 1].id, :pro => @pro, :des => @des, :hom => @hom, :off => @off, :top => @top, :par => @par, :ret => @ret, :eve => @eve, :reg => @reg, :dat => @dat, :rall => @rall) : retailers_show_path(:id => @r[@i.to_i - 1].id, :pro => @pro, :des => @des, :hom => @hom, :off => @off, :top => @top, :par => @par, :ret => @ret, :eve => @eve, :reg => @reg, :dat => @dat, :rall => @rall))
                   else
                 end

    @path_up = case
                    when @pro
                      products_products_retailers_path(:id => @pro, :pro => @pro, :des => @des, :hom => @hom, :off => @off, :top => @top, :par => @par, :ret => @ret, :eve => @eve, :reg => @reg, :dat => @dat)
                    when @ret
                      "/retailers/by_region/" + @ret
                    when @eve
                      events_events_retailers_path(:id => @eve, :pro => @pro, :des => @des, :hom => @hom, :off => @off, :top => @top, :par => @par, :ret => @ret, :eve => @eve, :reg => @reg, :dat => @dat)
                    else
                      retailers_all_path
                  end

    @path_right = case
                   when @pro
                     @r = Product.find(@pro).retailers
                     hash = Hash[@r.map.with_index.to_a]
                     @i = hash[@retailer]
                     @m = @r.count

                     (@i == (@m - 1) ? retailers_show_path(:id => @r[0].id, :pro => @pro, :des => @des, :hom => @hom, :off => @off, :top => @top, :par => @par, :ret => @ret, :eve => @eve, :reg => @reg, :dat => @dat, :rall => @rall) : retailers_show_path(:id => @r[@i.to_i + 1].id, :pro => @pro, :des => @des, :hom => @hom, :off => @off, :top => @top, :par => @par, :ret => @ret, :eve => @eve, :reg => @reg, :dat => @dat, :rall => @rall))
                    when @ret
                      @r = Retailer.where('region = ?', @ret)
                      hash = Hash[@r.map.with_index.to_a]
                      @i = hash[@retailer]
                      @m = @r.count

                      (@i == (@m - 1) ? retailers_show_path(:id => @r[0].id, :pro => @pro, :des => @des, :hom => @hom, :off => @off, :top => @top, :par => @par, :ret => @ret, :eve => @eve, :reg => @reg, :dat => @dat, :rall => @rall) : retailers_show_path(:id => @r[@i.to_i + 1].id, :pro => @pro, :des => @des, :hom => @hom, :off => @off, :top => @top, :par => @par, :ret => @ret, :eve => @eve, :reg => @reg, :dat => @dat, :rall => @rall))
                    when @eve
                      @r = Event.find(@eve).retailers
                      hash = Hash[@r.map.with_index.to_a]
                      @i = hash[@retailer]
                      @m = @r.count

                      (@i == (@m - 1) ? retailers_show_path(:id => @r[0].id, :pro => @pro, :des => @des, :hom => @hom, :off => @off, :top => @top, :par => @par, :ret => @ret, :eve => @eve, :reg => @reg, :dat => @dat, :rall => @rall) : retailers_show_path(:id => @r[@i.to_i + 1].id, :pro => @pro, :des => @des, :hom => @hom, :off => @off, :top => @top, :par => @par, :ret => @ret, :eve => @eve, :reg => @reg, :dat => @dat, :rall => @rall))
                    else
                  end
  end

  def retailers_products
    @retailer = Retailer.find(params[:id])

    @pro = params[:pro]
    @des = params[:des]
    @hom = params[:hom]
    @off = params[:off]
    @top = params[:top]
    @par = params[:par]
    @ret = params[:ret]
    @eve = params[:eve]
    @reg = params[:reg]
    @dat = params[:dat]
    @rall = params[:rall]
  end

  def regions
  end

  def where_we_are
    @retailer = Retailer.find(params[:id])

    @pro = params[:pro]
    @des = params[:des]
    @hom = params[:hom]
    @off = params[:off]
    @top = params[:top]
    @par = params[:par]
    @ret = params[:ret]
    @eve = params[:eve]
    @reg = params[:reg]
    @dat = params[:dat]
    @rall = params[:rall]

    if !@ret and !@rall and !@pro and !@eve
      @ret = @retailer.region
    end

    @path_left = case
                   when @pro
                     @r = Product.find(@pro).retailers
                     hash = Hash[@r.map.with_index.to_a]
                     @i = hash[@retailer]
                     @m = @r.count

                     (@i == 0 ? retailers_show_path(:id => @r[@m - 1].id, :pro => @pro, :des => @des, :hom => @hom, :off => @off, :top => @top, :par => @par, :ret => @ret, :eve => @eve, :reg => @reg, :dat => @dat, :rall => @rall) : retailers_show_path(:id => @r[@i.to_i - 1].id, :pro => @pro, :des => @des, :hom => @hom, :off => @off, :top => @top, :par => @par, :ret => @ret, :eve => @eve, :reg => @reg, :dat => @dat, :rall => @rall))
                   when @ret
                     @r = Retailer.where('region = ?', @ret)
                     hash = Hash[@r.map.with_index.to_a]
                     @i = hash[@retailer]
                     @m = @r.count

                     (@i == 0 ? retailers_show_path(:id => @r[@m - 1].id, :pro => @pro, :des => @des, :hom => @hom, :off => @off, :top => @top, :par => @par, :ret => @ret, :eve => @eve, :reg => @reg, :dat => @dat, :rall => @rall) : retailers_show_path(:id => @r[@i.to_i - 1].id, :pro => @pro, :des => @des, :hom => @hom, :off => @off, :top => @top, :par => @par, :ret => @ret, :eve => @eve, :reg => @reg, :dat => @dat, :rall => @rall))
                   when @eve
                     @r = Event.find(@eve).retailers
                     hash = Hash[@r.map.with_index.to_a]
                     @i = hash[@retailer]
                     @m = @r.count

                     (@i == 0 ? retailers_show_path(:id => @r[@m - 1].id, :pro => @pro, :des => @des, :hom => @hom, :off => @off, :top => @top, :par => @par, :ret => @ret, :eve => @eve, :reg => @reg, :dat => @dat, :rall => @rall) : retailers_show_path(:id => @r[@i.to_i - 1].id, :pro => @pro, :des => @des, :hom => @hom, :off => @off, :top => @top, :par => @par, :ret => @ret, :eve => @eve, :reg => @reg, :dat => @dat, :rall => @rall))
                   else
                 end

    @path_up = case
                 when @pro
                   products_products_retailers_path(:id => @pro, :pro => @pro, :des => @des, :hom => @hom, :off => @off, :top => @top, :par => @par, :ret => @ret, :eve => @eve, :reg => @reg, :dat => @dat)
                 when @ret
                   "/retailers/by_region/" + @ret
                 when @eve
                   events_events_retailers_path(:id => @eve, :pro => @pro, :des => @des, :hom => @hom, :off => @off, :top => @top, :par => @par, :ret => @ret, :eve => @eve, :reg => @reg, :dat => @dat)
                 else
                   retailers_all_path
               end

    @path_right = case
                    when @pro
                      @r = Product.find(@pro).retailers
                      hash = Hash[@r.map.with_index.to_a]
                      @i = hash[@retailer]
                      @m = @r.count

                      (@i == (@m - 1) ? retailers_show_path(:id => @r[0].id, :pro => @pro, :des => @des, :hom => @hom, :off => @off, :top => @top, :par => @par, :ret => @ret, :eve => @eve, :reg => @reg, :dat => @dat, :rall => @rall) : retailers_show_path(:id => @r[@i.to_i + 1].id, :pro => @pro, :des => @des, :hom => @hom, :off => @off, :top => @top, :par => @par, :ret => @ret, :eve => @eve, :reg => @reg, :dat => @dat, :rall => @rall))
                    when @ret
                      @r = Retailer.where('region = ?', @ret)
                      hash = Hash[@r.map.with_index.to_a]
                      @i = hash[@retailer]
                      @m = @r.count

app/helpers/retailers_helper.rb
module RetailersHelper
end

app/views/retailers/all.html.erb
<% content_for :orientation do %>
    rivenditori<span class="orientsep"> -> </span> <%= link_to "tutti i rivenditori", retailers_all_path %>
<% end %>

<% content_for :rightcol do %>
<h1>Ecco tutti i nostri venditori</h1>
<ul>
  <% @all_retailers.each do |retailer| %>
      <li class="productelem">
        <%=link_to image_tag(retailer.photo_url, :alt => retailer.name, :width => 300), retailers_show_path(:id => retailer.id, :rall => 'true')%>
        <a class="productname" href="retailers/show/<%=retailer.id%>"><%=retailer.name%></a>
      </li>
  <% end %>
</ul>
<% end %>

<% content_for :leftcol do %>
<% end %>

app/views/retailers/by_region.html.erb
<% content_for :orientation do%>
    rivenditori<span class="orientsep"> -> </span> <%= link_to @reg, ""%>
<% end %>

<% content_for :rightcol do %>
    <h1>Rivenditori regione <span class="enph"><%= @reg %></span></h1>
    <% if !@retailers_by_region[0] %> Non ci sono rivenditori in questa regione. <% else  %>
        <ul>
          <% @retailers_by_region.each do |retailer| %>
              <li class="productelem">
                <%=link_to image_tag(retailer.photo_url, :alt => retailer.name, :width => 300), retailers_show_path(:id => retailer.id, :ret => @reg)%>
                <a class="productname" href="retailers/show/<%=retailer.id%>"><%=retailer.name%></a>
              </li>
          <% end %>
        </ul>
    <% end %>
<% end %>

<% content_for :leftcol do %>
    <div class="row">
      <%= link_to retailers_regions_path do %>
          <%= image_tag("buttonbwd.png", :width => 40, :class => "icon") %><span class="pagesubtitle">Torna a regioni venditori</span>
      <% end %>
    </div>
<% end %>

app/views/retailers/new.html.erb
<% content_for :rightcol do %>
    <h1>Insert a new Retailer into the database</h1>


    <%= form_for(@retailer) do |f| %>
        <% if @retailer.errors.any? %>
            <div id="error_explanation">
              <h2><%= pluralize(@retailer.errors.count, "error") %> prohibited this post from being saved:</h2>

              <ul>
                <% @retailer.errors.full_messages.each do |msg| %>
                    <li><%= msg %></li>
                <% end %>
              </ul>
            </div>
        <% end %>

        <div class="field">
          <%= f.label :name %><br />
          <%= f.text_field :name %>
        </div>
        <div class="field">
          <%= f.label :description %><br />
          <%= f.text_area :description %>
        </div>
        <div class="field">
          <%= f.label :mail %> <br />
          <%= f.text_field :mail %>
        </div>
        <div class="field">
          <%= f.label :phone_number %> <br />
          <%= f.text_field :phone_number %>
        </div>
        <div class="field">
          <%= f.label :address %><br />
          <%= f.text_field :address %>
        </div>
        <div class="field"><br>
          <%= f.label :region %>
          <%= f.select :region, ["sicilia", "lombardia", "piemonte", "marche", "molise", "basilicata", "calabria", "sardegna", "puglia", "campania", "trentinoaltoadige", "friuliveneziagiulia", "valledaosta", "emiliaromanga", "lazio", "liguria", "toscana", "veneto", "umbria","abruzzo"] %>
        </div><br>
        <div class="actions">
          <%= f.submit %>
        </div>
    <% end %>

<% end %>

<% content_for :leftcol do %>
    <div class="row">
      <%= link_to "Back to Admin page", pages_admin_path %>
    </div>
<% end %>

app/views/retailers/retailers_products.html.erb
<% content_for :orientation do %>
    <%= link_to @retailer.name,  retailers_show_path(:id => @retailer.id, :ret => @retailer.region, :pro => @pro, :des => @des, :hom => @hom, :off => @off, :top => @top, :par => @par, :eve => @eve, :reg => @reg, :dat => @dat, :rall => @rall)%><span class="orientsep"> -> </span><%= link_to "prodotti","" %>
<% end %>

<% content_for :rightcol do %>
<h1>Ecco tutti i prodotti di <%= @retailer.name %></h1>
<ul>
  <% @retailer.products.each do |product| %>
      <li class="productelem">
        <% if (product.pictures[0]) %>
            <%=link_to image_tag(product.pictures[0].url_image, :alt => product.name, :width => 300), products_show_path(:id => product.id, :ret => @retailer.id, :pro => @pro, :des => @des, :hom => @hom, :off => @off, :top => @top, :par => @par, :eve => @eve, :reg => @reg, :dat => @dat, :rall => @rall)%>
        <% else %>
            <%=link_to image_tag("productdefault.jpg", :alt => product.name, :width => 300), products_show_path(:id => product.id, :ret => @retailer.id, :pro => @pro, :des => @des, :hom => @hom, :off => @off, :top => @top, :par => @par, :eve => @eve, :reg => @reg, :dat => @dat, :rall => @rall)%>
        <% end %>
        <%=link_to product.name, products_show_path(:id => product.id, :ret => @retailer.id, :pro => @pro, :des => @des, :hom => @hom, :off => @off, :top => @top, :par => @par, :eve => @eve, :reg => @reg, :dat => @dat, :rall => @rall), :class => "productname" %>
      </li>
  <% end %>
</ul>
<% end %>

<% content_for :leftcol do %>
    <div class="row">
      <%= link_to retailers_show_path(:id => @retailer.id, :ret => @ret, :pro => @pro, :des => @des, :hom => @hom, :off => @off, :top => @top, :par => @par, :eve => @eve, :reg => @reg, :dat => @dat, :rall => @rall) do %>
          <%= image_tag("buttonbwd.png", :width => 40, :class => "icon") %><span class="pagesubtitle">Torna a <%=@retailer.name%></span>
      <% end %>
    </div>
<% end %>

app/views/retailers/show.html.erb
<% content_for :orientation do %>
        rivenditori<span class="orientsep"> -> </span><%= link_to @retailer.name, "" %>
<% end %>

<% content_for :rightcol do %>
    <h1><%=@retailer.name%></h1>
    <%= image_tag(@retailer.photo_url, :width => 300, :class => "retailerimg") %>
    <p class="justified"><%=@retailer.description%></p>
    <div class="row">
      <div class="arrowcontainer">
        <% if @path_left %>
            <%=link_to @path_left do%>
                <%= image_tag("arrowleft.png", :width => 60, :class => "leftarrowpage")%>
            <% end %>
        <% end %>
        <% if @path_up %>
            <%=link_to @path_up do%>
                <%= image_tag("arrowup.png", :width => 60, :class => "uparrowpage")%>
            <% end %>
        <% end %>
        <% if @path_right %>
            <%=link_to @path_right do%>
                <%= image_tag("arrowright.png", :width => 60, :class => "rightarrowpage")%>
            <% end %>
        <% end %>
      </div>
    </div>
<% end %>

<% content_for :leftcol do %>
    <%= link_to retailers_where_we_are_path(:id => @retailer.id, :pro => @pro, :des => @des, :hom => @hom, :off => @off, :top => @top, :par => @par, :ret => @ret, :eve => @eve, :reg => @reg, :dat => @dat, :rall => @rall) do %>
        <div class="row">
          <%=image_tag("whereweareicon.png", :width => 40, :class => "icon")%> <span class="pagesubtitle">Dove siamo</span><span class="gray"><%=@retailer.name%></span>
        </div>
    <% end %>
    <%= link_to retailers_retailers_products_path(:id => @retailer.id, :pro => @pro, :des => @des, :hom => @hom, :off => @off, :top => @top, :par => @par, :ret => @ret, :eve => @eve, :reg => @reg, :dat => @dat, :rall => @rall) do %>
    <div class="row">
      <%=image_tag("productsicon.png", :width => 40, :class => "icon")%> <span class="pagesubtitle">Prodotti</span><span class="gray"><%=@retailer.name%></span>
    </div>
    <% end %>
    <div class="row">
      <%=image_tag("eventsicon.png", :width => 40, :class => "icon")%> <span class="pagesubtitle">Eventi</span><span class="gray"><%=@retailer.name%></span>
    </div>
    <% if !@retailer.events[0] %> Nessun evento associato. <% else %>
        <ul class="eventlist">
          <% @retailer.events.each do |event| %>
              <%= link_to events_show_path(:id => event.id, :ret => @retailer.id, :pro => @pro, :des => @des, :hom => @hom, :off => @off, :top => @top, :par => @par, :eve => @eve, :reg => @reg, :dat => @dat, :rall => @rall) do%>
                  <li class="eventobject"><p><%=event.date%></p><p>@<%=event.name+","+event.place%></p></li>
              <% end %>
          <% end %>
        </ul>
    <% end %>
<% end %>

app/views/retailers/where_we_are.html.erb
<% content_for :orientation do %>
    <%= link_to @retailer.name, retailers_show_path(:id => @retailer.id) %> <span class"orientsep"> -> </span> <%= link_to "dove siamo", retailers_where_we_are_path(:id => @retailer.id) %>
<% end %>

<% content_for :rightcol do %>

    <h1>Dove Siamo</h1>
    <%= @retailer.address %>
    <input id="address" type="hidden" value="<%= @retailer.address %>">
    <script src="https://maps.googleapis.com/maps/api/js?v=3.exp&sensor=false"></script>
    <script>
        var geocoder;
        var map;
        function initialize() {
            geocoder = new google.maps.Geocoder();
            var latlng = new google.maps.LatLng(-34.397, 150.644);
            var mapOptions = {
                zoom: 16,
                center: latlng,
                mapTypeId: google.maps.MapTypeId.ROADMAP
            }
            map = new google.maps.Map(document.getElementById('map-canvas'), mapOptions);
            codeAddress();
        }

        function codeAddress() {
            var address = document.getElementById('address').value;
            geocoder.geocode( { 'address': address}, function(results, status) {
                if (status == google.maps.GeocoderStatus.OK) {
                    map.setCenter(results[0].geometry.location);
                    var marker = new google.maps.Marker({
                        map: map,
                        position: results[0].geometry.location
                    });
                } else {
                    alert('Geocode was not successful for the following reason: ' + status);
                }
            });
        }

        google.maps.event.addDomListener(window, 'load', initialize);
    </script>
    <div id="map-canvas"></div>
    <div class="row">
      <div class="arrowcontainer">
        <% if @path_left %>
            <%=link_to @path_left do%>
                <%= image_tag("arrowleft.png", :width => 60, :class => "leftarrowpage")%>
            <% end %>
        <% end %>
        <% if @path_up %>
            <%=link_to @path_up do%>
                <%= image_tag("arrowup.png", :width => 60, :class => "uparrowpage")%>
            <% end %>
        <% end %>
        <% if @path_right %>
            <%=link_to @path_right do%>
                <%= image_tag("arrowright.png", :width => 60, :class => "rightarrowpage")%>
            <% end %>
        <% end %>
      </div>
    </div>
<% end %>


<% content_for :leftcol do %>
    <%= link_to retailers_show_path(:id => @retailer.id, :pro => @pro, :des => @des, :hom => @hom, :off => @off, :top => @top, :par => @par, :ret => @ret, :eve => @eve, :reg => @reg, :dat => @dat) do %>
        <div class="row">
          <%=image_tag("whoweareicon.png", :width => 40, :class => "icon")%> <span class="pagesubtitle">Chi siamo</span><span class="gray"><%=@retailer.name%></span>
        </div>
    <% end %>
    <%= link_to retailers_retailers_products_path(:id => @retailer.id, :pro => @pro, :des => @des, :hom => @hom, :off => @off, :top => @top, :par => @par, :ret => @ret, :eve => @eve, :reg => @reg, :dat => @dat) do %>
        <div class="row">
          <%=image_tag("productsicon.png", :width => 40, :class => "icon")%> <span class="pagesubtitle">Prodotti</span><span class="gray"><%=@retailer.name%></span>
        </div>
    <% end %>
    <div class="row">
      <%=image_tag("eventsicon.png", :width => 40, :class => "icon")%> <span class="pagesubtitle">Eventi</span><span class="gray"><%=@retailer.name%></span>
    </div>
    <ul class="eventlist">
      <% @retailer.events.each do |event| %>
          <%= link_to events_show_path(:id => event.id, :pro => @pro, :des => @des, :hom => @hom, :off => @off, :top => @top, :par => @par, :ret => @retailer.id, :eve => @eve, :reg => @reg, :dat => @dat) do%>
              <li class="eventobject"><p><%=event.date%></p><p>@<%=event.name+","+event.place%></p></li>
          <% end %>
      <% end %>
    </ul>
<% end %>