config/routes.rb
Xcompany::Application.routes.draw do
  root :to => 'pages#home'

  match "/designers/all", :to => 'designers#all'
  match "/designers/awards", :to => 'designers#awards'
  match "/designers/show", :to => 'designers#show'
  match "/designers/new", :to => 'designers#new'
  match '/designers/:id' => 'designers#show'
  match "/designers/" => 'designers#create'

  resources :designers

  match "/products/new_home" => 'products#new_home'
  match 'products/new_office' => 'products#home_office'
  match "/products/all_home", :to => 'products#all_home'
  match "/products/all_office", :to => 'products#all_office'
  match "/products/by_partners", :to => 'products#by_partners'
  match '/products/office_by_type/:category' => 'products#office_by_type'
  match '/products/office_by_type' => 'products#office_by_type'
  match '/products/home_by_type/:category' => 'products#home_by_type'
  match '/products/home_by_type' => 'products#home_by_type'
  match 'products/products_retailers' => 'products#products_retailers'
  match 'products/show' => 'products#show'
  match 'products/top' => 'products#top'
  match '/products/:id' => 'products#show'
  match "/products/" => 'products#create'

  resources :products

  match "/events/by_date", :to => 'events#by_date'
  match 'events/by_region/', :to => 'events#by_region'
  match "/events/events_products", :to => 'events#events_products'
  match "/events/events_retailers", :to => 'events#events_retailers'
  match "/events/show", :to => 'events#show'
  match "/events/new", :to => 'events#new'
  match '/events/:id' => 'events#show'
  match "/events/" => 'events#create'

  resources :events

  match "/retailers/all", :to => 'retailers#all'
  match 'retailers/by_region/:region', :to => 'retailers#by_region'
  match "/retailers/regions", :to => 'retailers#regions'
  match "/retailers/retailers_products", :to => 'retailers#retailers_products'
  match "/retailers/show", :to => 'retailers#show'
  match "/retailers/where_we_are", :to => 'retailers#where_we_are'
  match "/retailers/new", :to => 'retailers#new'
  match '/retailers/:id' => 'retailers#show'
  match "/retailers/" => 'retailers#create'

  resources :retailers

  match "/admin" => 'pages#admin'
  get "pages/new_product_designer_relation"
  get "pages/new_product_retailer_relation"
  get "pages/new_product_event_relation"
  get "pages/new_retailer_event_relation"
  get "pages/home"
  get "pages/admin"
  get "pages/who_we_are"
  get "pages/where_we_are"
  get "pages/contact_us"
  get "pages/work_with_us"
  get "pages/partners"
  get "pages/services"

   match ':controller(/:action(/:id))(.:format)'
end

app/models/event.rb
class Event < ActiveRecord::Base
  attr_accessible :date, :description, :name, :photo_url, :place, :region, :time

  has_many :reverse_products_events_relationships, foreign_key: "event_id", class_name:  "ProductsEventsRelationship", dependent:   :destroy
  has_many :products, through: :reverse_products_events_relationships, source: :product

  has_many :reverse_retailers_events_relationships, foreign_key: "event_id", class_name:  "RetailersEventsRelationship", dependent:   :destroy
  has_many :retailers, through: :reverse_retailers_events_relationships, source: :retailer

  validates :name, :presence => true
  validates :description, :presence => true
  validates :place, :presence => true
  validates :region, :presence => true
  validates :date, :presence => true

end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  def by_date
    @all_events = Event.all
    @dates = []
    @all_events.each do |event|
      @dates << event.date
    end
    @dates.uniq!
    @dates.sort_by! {|date| date}
  end

  def by_region
    @all_events = Event.all
    @regions = []
    @all_events.each do |event|
      @regions << event.region
    end
    @regions.uniq!
  end

  def show
    @event = Event.find(params[:id])

    @pro = params[:pro]
    @des = params[:des]
    @hom = params[:hom]
    @off = params[:off]
    @top = params[:top]
    @par = params[:par]
    @ret = params[:ret]
    @eve = params[:eve]
    @reg = params[:reg]
    @dat = params[:dat]
    @rall = params[:rall]

    if @des
      @t = Designer.find(@des)
      @desname = @t.name + @t.lastname
    end

    if @pro and @pro != '0'
      @t = Product.find(@pro)
      @proname = @t.name
    end

    @path_left = case
                   when @reg
                     @e = Event.where('region = ?', @reg)
                     hash = Hash[@e.map.with_index.to_a]
                     @i = hash[@event]
                     @m = @e.count

                     (@i == 0 ? events_show_path(:id => @e[@m - 1].id, :reg => @reg) : events_show_path(:id => @e[@i.to_i - 1].id, :reg => @reg))
                   when @dat
                     @e = Event.where('date = ?', @dat)
                     hash = Hash[@e.map.with_index.to_a]
                     @i = hash[@event]
                     @m = @e.count

                     (@i == 0 ? events_show_path(:id => @e[@m - 1].id, :dat => @dat) : events_show_path(:id => @e[@i.to_i - 1].id, :dat => @dat))
                   else
                 end

    @path_up = case
                 when @reg
                   events_by_region_path
                 when @dat
                   events_by_date_path
                 when @pro
                   products_show_path(:id => @pro, :des => @des, :hom => @hom, :off => @off, :top => @top, :par => @par, :ret => @ret, :eve => @eve, :reg => @reg, :dat => @dat, :rall => @rall)
                 when @ret
                   retailers_show_path(:id => @ret, :pro => @pro, :des => @des, :hom => @hom, :off => @off, :top => @top, :par => @par, :eve => @eve, :reg => @reg, :dat => @dat, :rall => @rall)
                 else
               end

    @path_right = case
                   when @reg
                     @e = Event.where('region = ?', @reg)
                     hash = Hash[@e.map.with_index.to_a]
                     @i = hash[@event]
                     @m = @e.count

                     (@i == (@m - 1) ? events_show_path(:id => @e[0].id, :reg => @reg) : events_show_path(:id => @e[@i.to_i + 1].id, :reg => @reg))
                   when @dat
                     @e = Event.where('date = ?', @dat)
                     hash = Hash[@e.map.with_index.to_a]
                     @i = hash[@event]
                     @m = @e.count

                     (@i == (@m - 1) ? events_show_path(:id => @e[0].id, :dat => @dat) : events_show_path(:id => @e[@i.to_i + 1].id, :dat => @dat))
                   else
                 end
  end

  def events_retailers
    @event = Event.find(params[:id])

    @pro = params[:pro]
    @des = params[:des]
    @hom = params[:hom]
    @off = params[:off]
    @top = params[:top]
    @par = params[:par]
    @ret = params[:ret]
    @eve = params[:eve]
    @reg = params[:reg]
    @dat = params[:dat]
    @rall = params[:rall]
  end

  def events_products
    @event = Event.find(params[:id])

    @pro = params[:pro]
    @des = params[:des]
    @hom = params[:hom]
    @off = params[:off]
    @top = params[:top]
    @par = params[:par]
    @ret = params[:ret]
    @eve = params[:eve]
    @reg = params[:reg]
    @dat = params[:dat]
    @rall = params[:rall]
  end

  def new
    @event = Event.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render :json => @event }
    end
  end

  def create
    @event = Event.new(params[:event])

    @event.photo_url = "eventdefault.jpg"

    respond_to do |format|
      if @event.save
        format.html { redirect_to pages_admin_path, :notice => 'Event was successfully created.' }
      else
        format.html { render :action => "new" }
      end
    end

  end
end

app/helpers/events_helper.rb
module EventsHelper
end

app/views/events/by_date.html.erb
<% content_for :orientation do %>
    <%=link_to "Eventi per data", events_by_date_path %>
<% end %>

<% content_for :rightcol do %>
<h1>Eventi (per data)</h1>
<h3>Calendario degli eventi nei quali potrete trovare i nostri prodotti:</h3>
<ul>
  <% @dates.each do |date| %>
      <p class="eventdate"><%= date.to_formatted_s(:rfc822) %></p>
      <ul class="eventlist">
        <% @all_events.each do |event| %>
            <li><% if date == event.date %> <%= link_to event.name+" @ "+event.place+" ("+event.region+")", events_show_path(:id => event.id, :dat => date) %> <% end %></li>
        <% end %>
      </ul>
  <% end %>
</ul>

<% end %>

<% content_for :leftcol do %>
<% end %>

app/views/events/by_region.html.erb
<% content_for :orientation do %>
    <%=link_to "Eventi per zona", events_by_region_path %>
<% end %>

<% content_for :rightcol do %>
<h1>Eventi (per zona)</h1>
<h3>Calendario degli eventi divisi per zona nei quali potrete trovare i nostri prodotti:</h3>
  <% @regions.each do |region| %>
      <p class="eventregion"><%= region %></p>
      <ul class="eventlist">
        <% @all_events.each do |event| %>
            <li><% if region == event.region %> <%= link_to event.name+" @ "+event.place+" ("+event.date.to_formatted_s(:rfc822)+")", events_show_path(:id => event.id, :reg => region) %> <% end %></li>
        <% end %>
      </ul>
  <% end %>
<% end %>

<% content_for :leftcol do %>
<% end %>

app/views/events/events_products.html.erb
<% content_for :orientation do %>
    <%= link_to @event.name,  events_show_path(:id => @event.id, :ret => @ret, :pro => @pro, :des => @des, :hom => @hom, :off => @off, :top => @top, :par => @par, :eve => @event.id, :reg => @reg, :dat => @dat, :rall => @rall)%><span class="orientsep"> -> </span><%= link_to "prodotti","" %>
<% end %>

<% content_for :rightcol do %>
    <h1>Ecco tutti i prodotti di <%= @event.name %></h1>
    <ul>
      <% @event.products.each do |product| %>
          <li class="productelem">
            <% if (product.pictures[0]) %>
                <%=link_to image_tag(product.pictures[0].url_image, :alt => product.name, :width => 300), products_show_path(:id => product.id, :ret => @ret, :pro => @pro, :des => @des, :hom => @hom, :off => @off, :top => @top, :par => @par, :eve => @event.id, :reg => @reg, :dat => @dat, :rall => @rall)%>
            <% else %>
                <%=link_to image_tag("productdefault.jpg", :alt => product.name, :width => 300), products_show_path(:id => product.id, :ret => @ret, :pro => @pro, :des => @des, :hom => @hom, :off => @off, :top => @top, :par => @par, :eve => @event.id, :reg => @reg, :dat => @dat, :rall => @rall)%>
            <% end %>
            <%= link_to product.name, products_show_path(:id => product.id, :ret => @ret, :pro => @pro, :des => @des, :hom => @hom, :off => @off, :top => @top, :par => @par, :eve => @event.id, :reg => @reg, :dat => @dat, :rall => @rall), :class => "productname" %>
          </li>
      <% end %>
    </ul>
<% end %>

<% content_for :leftcol do %>
    <div class="row">
      <%= link_to events_show_path(:id => @event.id, :ret => @ret, :pro => @pro, :des => @des, :hom => @hom, :off => @off, :top => @top, :par => @par, :eve => @eve, :reg => @reg, :dat => @dat, :rall => @rall) do %>
          <%= image_tag("buttonbwd.png", :width => 40, :class => "icon") %><span class="pagesubtitle">Torna a <%=@event.name%></span>
      <% end %>
    </div>
<% end %>

app/views/events/events_retailers.html.erb
<% content_for :orientation do %>
    <%=link_to @event.name ,events_show_path(:id => @event.id, :pro => @pro, :des => @des, :hom => @hom, :off => @off, :top => @top, :par => @par, :ret => @ret, :eve => @eve, :reg => @reg, :dat => @dat, :rall => @rall)%> <span class="orientsep"> -> </span> <%= link_to "rivenditori", events_events_retailers_path(:hom => @hom, :id => @event.id) %>
<% end %>

<% content_for :rightcol do %>
    <h1>Al <%= @event.name %> puoi trovare i seguenti rivenditori:</h1>

    <ul class="eventretailerslist">
      <% @event.retailers.each do |retailer| %>
          <li><%= link_to retailers_show_path(:id => retailer.id, :pro => @pro, :des => @des, :hom => @hom, :off => @off, :top => @top, :par => @par, :ret => @ret, :eve => @event.id, :reg => @reg, :dat => @dat, :rall => @rall) do %>
                <%= image_tag(retailer.photo_url, :width => 200, :class => "retailerphoto")%> <span class="retailerername"><%=retailer.name+": "+retailer.region %></span>
            <% end %></li>
      <% end %>
    </ul>
<% end %>

<% content_for :leftcol do %>
    <div class="row">
      <%= link_to events_show_path(:id => @event.id, :pro => @pro, :des => @des, :hom => @hom, :off => @off, :top => @top, :par => @par, :ret => @ret, :eve => @event.id, :reg => @reg, :dat => @dat, :rall => @rall) do %>
          <%= image_tag("buttonbwd.png", :width => 40, :class => "icon") %><span class="pagesubtitle">Torna a</span><span class="gray"><%=@event.name%></span>
      <% end %>
    </div>
<% end %>

app/views/events/new.html.erb
<% content_for :rightcol do %>
    <h1>Insert a new Event into the database</h1>


    <%= form_for(@event) do |f| %>
        <% if @event.errors.any? %>
            <div id="error_explanation">
              <h2><%= pluralize(@event.errors.count, "error") %> prohibited this post from being saved:</h2>

              <ul>
                <% @event.errors.full_messages.each do |msg| %>
                    <li><%= msg %></li>
                <% end %>
              </ul>
            </div>
        <% end %>

        <div class="field">
          <%= f.label :name %><br />
          <%= f.text_field :name %>
        </div>
        <div class="field">
          <%= f.label :description %><br />
          <%= f.text_area :description %>
        </div>
        <div class="field">
          <%= f.label :date %> (dd-mm-yyyy)<br />
          <%= f.text_field :date %>
        </div>
        <div class="field">
          <%= f.label :time %> (hh:mm:ss)<br />
          <%= f.text_field :time %>
        </div>
        <div class="field">
          <%= f.label :address %><br />
          <%= f.text_field :place %>
        </div>
        <div class="field"><br>
          <%= f.label :region %>
          <%= f.select :region, ["sicilia", "lombardia", "piemonte", "marche", "molise", "basilicata", "calabria", "sardegna", "puglia", "campania", "trenitino", "friuli", "valledaosta", "emiliaromanga", "lazio", "liguria", "toscana", "veneto", "umbria","abruzzo"] %>
        </div><br>
        <div class="actions">
            <%= f.submit %>
        </div>
    <% end %>

<% end %>

<% content_for :leftcol do %>
    <div class="row">
      <%= link_to "Back to Admin page", pages_admin_path %>
    </div>
<% end %>

app/views/events/show.html.erb
<% content_for :orientation do %>
    <% if(@reg) %>
        <%= link_to "Eventi per zona: "+@reg, events_by_region_path %><span class="orientsep"> -> </span><%= link_to @event.date.to_formatted_s(:rfc822)+" - "+@event.name, ""%>
    <% elsif(@dat) %>
        <%= link_to "Eventi per data", events_by_date_path %><span class="orientsep"> -> </span><%= link_to @event.date.to_formatted_s(:rfc822)+" - "+@event.name, ""%>
    <% elsif(@des)%>
        <%= link_to "Designers", designers_all_path%><span class="orientsep"> -> </span><%= link_to @desname, designers_show_path(:id => @des)%><span class="orientsep"> -> </span><%= link_to @proname, products_show_path(:des => @des,:id => @pro, :pro => @pro)%><span class="orientsep"> -> </span><%= link_to @event.name,""%>
    <% end %>
<% end %>
<% content_for :rightcol do %>
<h1><%=@event.name%></h1>
<%=image_tag(@event.photo_url, :class => "eventphoto")%>
<div class="row">
  <%=image_tag("formatbullets.png", :width => 40, :class => "icon")%> <span class="pagesubtitle">Descrizione</span>
</div>
<p class="paragraph"><%=@event.description %></p>
<div class="row">
  <%=image_tag("dataicon.png", :width => 40, :class => "icon")%> <span class="pagesubtitle">Data: <%=@event.date.to_formatted_s(:rfc822)%></span>
</div>
<div class="row">
  <%=image_tag("oraicon.png", :width => 40, :class => "icon")%> <span class="pagesubtitle">Ora: <%=@event.time.strftime("%I:%M")%></span>
</div>
<div class="row">
  <%=image_tag("locationicon.png", :width => 40, :class => "icon")%> <span class="pagesubtitle">Location: <%=@event.place%>, <%=@event.region%></span>
</div>

<div class="row">
  <div class="arrowcontainer">
    <% if @path_left %>
        <%=link_to @path_left do%>
            <%= image_tag("arrowleft.png", :width => 60, :class => "leftarrowpage")%>
        <% end %>
    <% end %>
    <% if @path_up %>
        <%=link_to @path_up do%>
            <%= image_tag("arrowup.png", :width => 60, :class => "uparrowpage")%>
        <% end %>
    <% end %>
    <% if @path_right %>
        <%=link_to @path_right do%>
            <%= image_tag("arrowright.png", :width => 60, :class => "rightarrowpage")%>
        <% end %>
    <% end %>
  </div>
</div>
</div>
<% end %>

<% content_for :leftcol do %>
<div class="row">
  <%= link_to events_events_retailers_path(:id => @event.id, :pro => @pro, :des => @des, :hom => @hom, :off => @off, :top => @top, :par => @par, :ret => @ret, :eve => @eve, :reg => @reg, :dat => @dat, :rall => @rall) do %>
      <%= image_tag("resellersicon.png", :width => 40, :class => "icon") %><span class="pagesubtitle">Rivenditori</span>
  <% end %>
</div>
    <div class="row">
      <%= link_to events_events_products_path(:id => @event.id, :pro => @pro, :des => @des, :hom => @hom, :off => @off, :top => @top, :par => @par, :ret => @ret, :eve => @eve, :reg => @reg, :dat => @dat, :rall => @rall) do %>
          <%= image_tag("productsicon.png", :width => 40, :class => "icon") %><span class="pagesubtitle">Prodotti</span>
      <% end %>
    </div>

<% end %>