config/routes.rb
Xcompany::Application.routes.draw do
  root :to => 'pages#home'

  match "/designers/all", :to => 'designers#all'
  match "/designers/awards", :to => 'designers#awards'
  match "/designers/show", :to => 'designers#show'
  match "/designers/new", :to => 'designers#new'
  match '/designers/:id' => 'designers#show'
  match "/designers/" => 'designers#create'

  resources :designers

  match "/products/new_home" => 'products#new_home'
  match 'products/new_office' => 'products#home_office'
  match "/products/all_home", :to => 'products#all_home'
  match "/products/all_office", :to => 'products#all_office'
  match "/products/by_partners", :to => 'products#by_partners'
  match '/products/office_by_type/:category' => 'products#office_by_type'
  match '/products/office_by_type' => 'products#office_by_type'
  match '/products/home_by_type/:category' => 'products#home_by_type'
  match '/products/home_by_type' => 'products#home_by_type'
  match 'products/products_retailers' => 'products#products_retailers'
  match 'products/show' => 'products#show'
  match 'products/top' => 'products#top'
  match '/products/:id' => 'products#show'
  match "/products/" => 'products#create'

  resources :products

  match "/events/by_date", :to => 'events#by_date'
  match 'events/by_region/', :to => 'events#by_region'
  match "/events/events_products", :to => 'events#events_products'
  match "/events/events_retailers", :to => 'events#events_retailers'
  match "/events/show", :to => 'events#show'
  match "/events/new", :to => 'events#new'
  match '/events/:id' => 'events#show'
  match "/events/" => 'events#create'

  resources :events

  match "/retailers/all", :to => 'retailers#all'
  match 'retailers/by_region/:region', :to => 'retailers#by_region'
  match "/retailers/regions", :to => 'retailers#regions'
  match "/retailers/retailers_products", :to => 'retailers#retailers_products'
  match "/retailers/show", :to => 'retailers#show'
  match "/retailers/where_we_are", :to => 'retailers#where_we_are'
  match "/retailers/new", :to => 'retailers#new'
  match '/retailers/:id' => 'retailers#show'
  match "/retailers/" => 'retailers#create'

  resources :retailers

  match "/admin" => 'pages#admin'
  get "pages/new_product_designer_relation"
  get "pages/new_product_retailer_relation"
  get "pages/new_product_event_relation"
  get "pages/new_retailer_event_relation"
  get "pages/home"
  get "pages/admin"
  get "pages/who_we_are"
  get "pages/where_we_are"
  get "pages/contact_us"
  get "pages/work_with_us"
  get "pages/partners"
  get "pages/services"

   match ':controller(/:action(/:id))(.:format)'
end

app/views/pages/admin.html.erb
<% content_for :orientation do %>
    <%= link_to "admin page", pages_admin_path %>
<% end %>

<% content_for :rightcol do %>
    <h1>Admin Page</h1>
    <ul>
      <li> <%= link_to "- Insert new designer", designers_new_path %> </li>
      <li> <%= link_to "- Insert new home product", products_new_home_path %> </li>
      <li> <%= link_to "- Insert new event", events_new_path %> </li>
      <li> <%= link_to "- Insert new retailer", retailers_new_path %> </li>
      <li> <%= link_to "- Insert new product-designer association", pages_new_product_designer_relation_path %> </li>
      <li> <%= link_to "- Insert new product-retailer association", pages_new_product_retailer_relation_path %> </li>
      <li> <%= link_to "- Insert new product-event association", pages_new_product_event_relation_path %> </li>
      <li> <%= link_to "- Insert new retailer-event association", pages_new_retailer_event_relation_path %> </li>
    </ul>

<% end %>

app/views/pages/contact_us.html.erb
<% content_for :orientation do %>
    <%= link_to "contatti", pages_contact_us_path %>
<% end %>

<% content_for :rightcol do %>
    <h1>Contatti</h1>
    <h3>Per i clienti:</h3>
    <ul>
      <li> Telefono: 095 7551321</li>
      <li> Mail: infoclienti@compagniax.com</li>
      <li> Fax: 02 26683287</li>
    </ul>

    <h3>Per i rivenditori:</h3>
    <ul>
      <li> Telefono: 02 26681577</li>
      <li> Mail: inforivenditori@compagniax.com</li>
      <li> Fax: 02 26682539</li>
    </ul>

<% end %>

<% content_for :leftcol do %>
    <div class="row">
      <%= link_to pages_work_with_us_path do %>
          <%= image_tag("riconoscimenti.png", :width => 40, :class => "icon") %><span class="pagesubtitle">Diventa Partner</span>
      <% end %>
    </div>
<% end %>

app/views/pages/home.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Xcompany <%= @title%></title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
<div id="home">
<div id="hometop">
  <div class="linkcontainer">
    <div class="menuitem"><%= link_to "rivenditori", retailers_regions_path %></div>
    <div class="menuitem"><a id="prodotti" >Prodotti</a>
        <div class="prodottisubmenu submenu">
          <ul>
            <li><%= link_to "prodotti casa", products_all_home_path %></li>
            <li><%= link_to "prodotti ufficio", products_all_office_path %></li>
            <li><%= link_to "prodotti top", products_top_path %></li>
            <li><%= link_to "prodotti partners", products_by_partners_path %></li>
          </ul>
        </div>
      </div>
      <div class="menuitem">
      <%= link_to "Servizi", pages_services_path%>
      </div>
  </div>
</div>
<div id="homebottom">
    <%=link_to image_tag("xcompanylogostroked.png", :alt => "XCompanyLogo", :class => "headerlogo", :width => 300), pages_home_path%>
  <div class="bottomlinkcontainer">
    <div class="menuitem"><%= link_to "Designers", designers_all_path()%></div>
    <div class="menuitem"><a id="eventi">Eventi</a>
    <div class="eventisubmenu submenubottom">
      <ul>
        <li><%= link_to "eventi per data", events_by_date_path%></li>
        <li><%= link_to "eventi per zona", events_by_region_path %></li>
      </ul>
    </div>
    </div>
    <div class="menuitem"><%= link_to "Partners", pages_partners_path()%></div>
    <div class="menuitem"><%= link_to "Chi siamo", pages_who_we_are_path()%></div>
    <div class="menuitem"><%= link_to "Contatti", pages_contact_us_path()%></div>
  </div>
</div>
</div>
</body>
</html>

app/views/pages/new_product_designer_relation.html.erb
<% content_for :rightcol do %>
    <h1>Associate a product with a designer</h1>

    <%= form_tag({:controller => "pages", :action => "create_product_designer_relation"}, :method => "post") do%>

        <div class="field">
            <%= label_tag(:product_label, "Product:") %>
            <%= select_tag "product", options_from_collection_for_select(@products, "id", "name") %>

            <%= label_tag(:designer_label, "<--->  Designer:") %>
            <%= select_tag "designer", options_from_collection_for_select(@designers, "id", "name") %>
        </div> <br>
        <div class="submit" style="text-align: center">
            <%= submit_tag("Submit") %>
        </div>
    <% end %>

<% end %>

<% content_for :leftcol do %>
    <div class="row">
      <%= link_to "Back to Admin page", pages_admin_path %>
    </div>
<% end %>

app/views/pages/new_product_event_relation.html.erb
<% content_for :rightcol do %>
    <h1>Associate a product with an event</h1>



    <%= form_tag({:controller => "pages", :action => "create_product_event_relation"}, :method => "post") do%>

        <div class="field">
            <%= label_tag(:product_label, "Product:") %>
            <%= select_tag "product", options_from_collection_for_select(@products, "id", "name") %>

            <%= label_tag(:event_label, "<--->  Event:") %>
            <%= select_tag "event", options_from_collection_for_select(@events, "id", "name") %>
        </div> <br>
        <div class="submit" style="text-align: center">
            <%= submit_tag("Submit") %>
        </div>
    <% end %>

<% end %>

<% content_for :leftcol do %>
    <div class="row">
      <%= link_to "Back to Admin page", pages_admin_path %>
    </div>
<% end %>

app/views/pages/new_product_retailer_relation.html.erb
<% content_for :rightcol do %>
    <h1>Associate a product with a retailer</h1>



    <%= form_tag({:controller => "pages", :action => "create_product_retailer_relation"}, :method => "post") do%>

        <div class="field">
            <%= label_tag(:product_label, "Product:") %>
            <%= select_tag "product", options_from_collection_for_select(@products, "id", "name") %>

            <%= label_tag(:retailer_label, "<--->  Retailer:") %>
            <%= select_tag "retailer", options_from_collection_for_select(@retailers, "id", "name") %>
        </div> <br>
        <div class="submit" style="text-align: center">
            <%= submit_tag("Submit") %>
        </div>
    <% end %>

<% end %>

<% content_for :leftcol do %>
    <div class="row">
      <%= link_to "Back to Admin page", pages_admin_path %>
    </div>
<% end %>

app/views/pages/new_retailer_event_relation.html.erb
<% content_for :rightcol do %>
    <h1>Associate a retailer with an event</h1>



    <%= form_tag({:controller => "pages", :action => "create_retailer_event_relation"}, :method => "post") do%>

        <div class="field">
            <%= label_tag(:retailer_label, "Retailer:") %>
            <%= select_tag "retailer", options_from_collection_for_select(@retailers, "id", "name") %>

            <%= label_tag(:event_label, "<--->  Event:") %>
            <%= select_tag "event", options_from_collection_for_select(@events, "id", "name") %>
        </div> <br>
        <div class="submit" style="text-align: center">
            <%= submit_tag("Submit") %>
        </div>
    <% end %>

<% end %>

<% content_for :leftcol do %>
    <div class="row">
      <%= link_to "Back to Admin page", pages_admin_path %>
    </div>
<% end %>

app/views/pages/partners.html.erb
<% content_for :orientation do %>
    <%= link_to "partners", pages_partners_path %>
<% end %>

<% content_for :rightcol do %>
    <h1>Partners</h1>
    <h3>Da anni collaboriamo con i seguenti partners:</h3>
    <div class="pageobject">
        <a href="#">
          <%= image_tag("molteni.jpg", :width => 290)%>
          <p>Molteni&C</p>
        </a>
    </div>
    <div class="pageobject">
        <a href="#">
          <%= image_tag("citterio.jpg", :width => 290) %>
          <p>Citterio</p>
        </a>
    </div>
    <div class="pageobject">
         <a href="#">
           <%= image_tag("unifor.jpg", :width => 290) %>
           <p>Unifor</p>
         </a>
    </div>
    <div class="pageobject">
         <a href="#">
           <%= image_tag("dada.jpg", :width => 290) %>
           <p>Dada</p>
         </a>
    </div>

<% end %>

<% content_for :leftcol do %>
<% end %>

app/views/pages/services.html.erb
<% content_for :orientation do %>
    <a href="/pages/services">Servizi offerti</a>
<% end %>

<% content_for :rightcol do %>
    <h1>Servizi</h1>
    <h2>Servizi offerti ai clienti:</h2>

    <h3 class="servicesubtitle">Personalizzazione</h3>
    <p>Molti dei nostri prodotti possono essere modificati secondo le
       particolari esigenze dei nostri clienti, in particolare possono
       variare i colori e i materiali di realizzazione di alcuni inserti.
       Inoltre, data la struttur fortemente modulare di alcuni prodotti,
       è possibile adattarli alle forme e dimensioni dei luoghi in cui
       devono andare.
    </p>

    <h3 class="servicesubtitle">Design di interni</h3>
    <p>La compagnia mette a disposizione alcuni suoi architetti e designer
      di interni per aiutare i clienti a realizzare i trasformare in realtà i propri sogni,
      progettando ambienti confortevoli e pieni di stile
    </p>

    <h3 class="servicesubtitle">Assistenza</h3>
    <p>La compagnia mette a disposizione dei propri clienti, siano essi acquirenti o rivenditori,
      un insieme di servizi telefonici e telematici. Le soluzioni proposte, attraverso il
      telefono (ESPOC), attraverso internet (CEWSS) o tramite i Centri Autorizzati, offrono
      una serie di informazioni e di servizi per poter utilizzare al meglio e mantenere efficiente
      qualsiasi prodotto.
    </p>

    <h3 class="servicesubtitle">Riparazione</h3>
    <p>In caso di danni ai nostri prodotti coperti da garanzia, la compagnia si impegna alla
      completa riparazione (o sostituzione) facendosi completamente carico di tutte le eventuali
      spese di trasporto.
    </p>


<% end %>

<% content_for :leftcol do %>
<% end %>

app/views/pages/where_we_are.html.erb
<% content_for :orientation do %>
    <%= link_to "la compagnia", pages_who_we_are_path %> <span class"orientsep"> -> </span> <%= link_to "dove siamo", pages_where_we_are_path %>
<% end %>

<% content_for :rightcol do %>
    <h1>Dove Siamo</h1>
    <br>
    <p>Via Antonio Gramsci, 57 Comano (MI)</p>
    <br>
    <iframe width="650" height="550" frameborder="0" scrolling="no" marginheight="0" marginwidth="0" src="http://maps.google.it/maps?f=q&amp;source=s_q&amp;hl=it&amp;geocode=&amp;q=Via+Antonio+Gramsci,+57,+Cormano,+MI&amp;aq=3&amp;oq=via+antonio+gramsci+57&amp;sll=45.468318,9.171867&amp;sspn=0.09342,0.237236&amp;ie=UTF8&amp;hq=&amp;hnear=Via+Antonio+Gramsci,+57,+Cormano,+Milano,+Lombardia&amp;ll=45.538655,9.165257&amp;spn=0.013166,0.032959&amp;t=m&amp;z=14&amp;output=embed"></iframe><br /><small><a href="http://maps.google.it/maps?f=q&amp;source=embed&amp;hl=it&amp;geocode=&amp;q=Via+Antonio+Gramsci,+57,+Cormano,+MI&amp;aq=3&amp;oq=via+antonio+gramsci+57&amp;sll=45.468318,9.171867&amp;sspn=0.09342,0.237236&amp;ie=UTF8&amp;hq=&amp;hnear=Via+Antonio+Gramsci,+57,+Cormano,+Milano,+Lombardia&amp;ll=45.538655,9.165257&amp;spn=0.013166,0.032959&amp;t=m&amp;z=14" style="color:#0000FF;text-align:left"></a></small>

<% end %>

<% content_for :leftcol do %>
    <div class="row">
      <%= link_to pages_who_we_are_path do %>
          <%= image_tag("whoweareicon.png", :width => 40, :class => "icon") %><span class="pagesubtitle">Chi Siamo</span>
      <% end %>
    </div>
<% end %>

app/views/pages/who_we_are.html.erb
<% content_for :orientation do %>
    <a href="/pages/who_we_are">Chi siamo</a>
<% end %>

<% content_for :rightcol do %>
    <h1>Chi Siamo</h1>

    <p class="pageparagraph">XCompany è una compagnia dedita al miglioramento della qualità delle abitazioni
      sfruttando la forza e la bellezza proprie del design.</p>
    <p class="pageparagraph">I nostri prodotti e concept sono il risultato di un intenso processo di design,
    derivante dalla stretta collaborazione dei nostri eccellenti ingegneri con alcuni
    designers di fama mondiale. È nostro obiettivo creare interni, mobili ed accessori
    per ambienti che siano funzionali ma allo stesso tempo accattivanti ed in stile
    moderno. Prestiamo grande attenzione inoltre nella scelta dei materiali e dei processi
    di fabbricazione dei prodotti che esponiamo, in modo da garantire sempre
    la massima qualità per i nostri clienti di ieri, di oggi e di domani.</p>
    <p class="pageparagraph">Collaboriamo inoltre con alcune aziende di grande rilievo come <span class="blue">MOLTENI&C</span>,
      <span class="blue">CITTERIO</span>,<span class="blue">DADA</span> ed <span class="blue">UNIFOR</span>
    per dare ai nostri clienti una scelta ancora più ampia di prodotti per poter arredare i loro ambienti
    nel modo che più li aggrada.</p>
    <p class="pageparagraph">Partecipiamo inoltre ad eventi su tutto il territorio nazionale nei quali presentiamo
       ed esponiamo i nostri prodotti insieme a quelli dei nostri partners.</p>
    <p class="pageparagraph">Offriamo anche servii di PERSONALIZZAZIONE, CONSULENZA DI DESIGN DI INTERNI, ASSISTENZA
     PRE E POST VENDITA E RIPARAZIONE.</p>
    <p class="pageparagraph">SEDE LEGALE: Via Antonio Gramsci, 57 Comano (MI)</p>


<% end %>

<% content_for :leftcol do %>
    <div class="row">
      <%= link_to pages_where_we_are_path do %>
          <%= image_tag("whereweareicon.png", :width => 40, :class => "icon") %><span class="pagesubtitle">Dove Siamo</span>
      <% end %>
    </div>
<% end %>

app/views/pages/work_with_us.html.erb
<% content_for :orientation do %>
    <%= link_to "contatti", pages_contact_us_path %> <span class"orientsep"> -> </span> <%= link_to "diventa partner", pages_work_with_us_path %>
<% end %>

<% content_for :rightcol do %>
    <h1>Diventa Partner</h1>

    <form id="form" action="#" method="post">
      <h3> Compila il form per effettuare la richiesta:</h3>
      <table id="table1"; cellspacing="5px" cellpadding="5%";>
      <tr>
        <td align="right">Nome rivenditore:</td>
        <td><input type="text" name="Company Name" /></td>
      </tr>
      <tr>
        <td align="right">Descrizione:</td>
        <td><textarea rows="6" cols="30" name="Description"></textarea>
          <p>Breve descrizione del vostro lavoro</p>
        </td>
      </tr>
      <tr>
        <td align="right">Numero di telefono:</td>
        <td><input type="text" name="Contact number" /></td>
      </tr>
      <tr>
        <td align="right">Persona di riferimento:</td>
        <td><input type="text" name="Contact person" /></td>
      </tr>
      <tr>
        <td valign="top" align="right">Email:</td>
        <td><input type="text" name="Email" /></td>
      </tr>
      <tr>
        <td align="right">Indirizzo: </td>
        <td><input type="text" name="locations" /></td>
      </tr>
      <tr>
        <td> </td>
        <td> <input type="submit" value="Invia" />
        </td>
      </tr>
      </table>
    </form>

<% end %>

<% content_for :leftcol do %>
    <div class="row">
      <%= link_to pages_contact_us_path do %>
          <%= image_tag("riconoscimenti.png", :width => 40, :class => "icon") %><span class="pagesubtitle">Contatti</span>
      <% end %>
    </div>
<% end %>