config/routes.rb
Xcompany::Application.routes.draw do
  root :to => 'pages#home'

  match "/designers/all", :to => 'designers#all'
  match "/designers/awards", :to => 'designers#awards'
  match "/designers/show", :to => 'designers#show'
  match "/designers/new", :to => 'designers#new'
  match '/designers/:id' => 'designers#show'
  match "/designers/" => 'designers#create'

  resources :designers

  match "/products/new_home" => 'products#new_home'
  match 'products/new_office' => 'products#home_office'
  match "/products/all_home", :to => 'products#all_home'
  match "/products/all_office", :to => 'products#all_office'
  match "/products/by_partners", :to => 'products#by_partners'
  match '/products/office_by_type/:category' => 'products#office_by_type'
  match '/products/office_by_type' => 'products#office_by_type'
  match '/products/home_by_type/:category' => 'products#home_by_type'
  match '/products/home_by_type' => 'products#home_by_type'
  match 'products/products_retailers' => 'products#products_retailers'
  match 'products/show' => 'products#show'
  match 'products/top' => 'products#top'
  match '/products/:id' => 'products#show'
  match "/products/" => 'products#create'

  resources :products

  match "/events/by_date", :to => 'events#by_date'
  match 'events/by_region/', :to => 'events#by_region'
  match "/events/events_products", :to => 'events#events_products'
  match "/events/events_retailers", :to => 'events#events_retailers'
  match "/events/show", :to => 'events#show'
  match "/events/new", :to => 'events#new'
  match '/events/:id' => 'events#show'
  match "/events/" => 'events#create'

  resources :events

  match "/retailers/all", :to => 'retailers#all'
  match 'retailers/by_region/:region', :to => 'retailers#by_region'
  match "/retailers/regions", :to => 'retailers#regions'
  match "/retailers/retailers_products", :to => 'retailers#retailers_products'
  match "/retailers/show", :to => 'retailers#show'
  match "/retailers/where_we_are", :to => 'retailers#where_we_are'
  match "/retailers/new", :to => 'retailers#new'
  match '/retailers/:id' => 'retailers#show'
  match "/retailers/" => 'retailers#create'

  resources :retailers

  match "/admin" => 'pages#admin'
  get "pages/new_product_designer_relation"
  get "pages/new_product_retailer_relation"
  get "pages/new_product_event_relation"
  get "pages/new_retailer_event_relation"
  get "pages/home"
  get "pages/admin"
  get "pages/who_we_are"
  get "pages/where_we_are"
  get "pages/contact_us"
  get "pages/work_with_us"
  get "pages/partners"
  get "pages/services"

   match ':controller(/:action(/:id))(.:format)'
end

app/models/product.rb
class Product < ActiveRecord::Base
  attr_accessible :description, :home_office, :name, :partner, :services, :top, :category, :designers

  validates :name, :presence => true
  validates :description, :presence => true
  validates :services, :presence => true
  validates :category, :presence => true
  validates :home_office, :presence => true

  has_many :products_designers_relationships, foreign_key: "product_id", dependent: :destroy
  has_many :designers, through: :products_designers_relationships, source: :designer

  has_many :products_retailers_relationships, foreign_key: "product_id", dependent: :destroy
  has_many :retailers, through: :products_retailers_relationships, source: :retailer

  has_many :products_events_relationships, foreign_key: "product_id", dependent: :destroy
  has_many :events, through: :products_events_relationships, source: :event

  has_many :pictures, foreign_key: "product_id", dependent: :destroy

end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  def office_by_type
    @office_prod = Product.where('partner = "f" AND home_office = "f" AND category = ?', params[:category])
    @cat = params[:category]
  end

  def home_by_type
    @home_prod = Product.where('partner = "f" AND home_office = "t" AND category = ?', params[:category])
    @cat = params[:category]
  end

  def by_partners
    @partners_prod = Product.where('partner = "t"')
  end

  def top
    @top_prod = Product.where('top = "t"')
  end

  def show
    @product = Product.find(params[:id])

    @pro = params[:pro]
    @des = params[:des]
    @hom = params[:hom]
    @off = params[:off]
    @top = params[:top]
    @par = params[:par]
    @ret = params[:ret]
    @eve = params[:eve]
    @reg = params[:reg]
    @dat = params[:dat]
    @rall = params[:rall]

    if @pro and @pro != '0'
      @t = Product.find(@pro)
      @proname = @t.name
    end

    if @des
      @t = Designer.find(@des)
      @desname = @t.name + @t.lastname
    end

    if @ret
      @t = Retailer.find(@ret)
      @retname = @t.name
    end

    if @eve
      @t = Event.find(@eve)
      @evename = @t.name
    end

    @path_left = case
                   when @des
                     @p = Designer.find(@des).designed_products
                     hash = Hash[@p.map.with_index.to_a]
                     @i = hash[@product]
                     @m = @p.count

                     (@i == 0 ? products_show_path(:id => @p[@m - 1].id, :pro => @pro, :des => @des, :hom => @hom, :off => @off, :top => @top, :par => @par, :ret => @ret, :eve => @eve, :reg => @reg, :dat => @dat, :rall => @rall) : products_show_path(:id => @p[@i.to_i - 1].id, :pro => @pro, :des => @des, :hom => @hom, :off => @off, :top => @top, :par => @par, :ret => @ret, :eve => @eve, :reg => @reg, :dat => @dat, :rall => @rall))
                   when (@hom and @product.category == @hom)
                     @p = Product.where('category = ?', @hom)
                     hash = Hash[@p.map.with_index.to_a]
                     @i = hash[@product]
                     @m = @p.count

                     (@i == 0 ? products_show_path(:id => @p[@m - 1].id, :pro => @pro, :hom => @hom, :des => @des, :off => @off, :top => @top, :par => @par, :ret => @ret, :eve => @eve, :reg => @reg, :dat => @dat, :rall => @rall) : products_show_path(:id => @p[@i.to_i - 1].id, :pro => @pro, :hom => @hom, :des => @des, :off => @off, :top => @top, :par => @par, :ret => @ret, :eve => @eve, :reg => @reg, :dat => @dat, :rall => @rall))
                   when (@off and @product.category == @off)
                     @p = Product.where('category = ?', @off)
                     hash = Hash[@p.map.with_index.to_a]
                     @i = hash[@product]
                     @m = @p.count

                     (@i == 0 ? products_show_path(:id => @p[@m - 1].id, :pro => @pro, :off => @off, :des => @des, :hom => @hom, :top => @top, :par => @par, :ret => @ret, :eve => @eve, :reg => @reg, :dat => @dat, :rall => @rall) : products_show_path(:id => @p[@i.to_i - 1].id, :pro => @pro, :off => @off, :des => @des, :hom => @hom, :top => @top, :par => @par, :ret => @ret, :eve => @eve, :reg => @reg, :dat => @dat, :rall => @rall))
                   when (@top and @product.top == true)
                     @p = Product.where('top = "t"')
                     hash = Hash[@p.map.with_index.to_a]
                     @i = hash[@product]
                     @m = @p.count

                     (@i == 0 ? products_show_path(:id => @p[@m - 1].id, :pro => @pro, :top => @top, :des => @des, :hom => @hom, :off => @off, :par => @par, :ret => @ret, :eve => @eve, :reg => @reg, :dat => @dat, :rall => @rall) : products_show_path(:id => @p[@i.to_i - 1].id, :pro => @pro, :top => @top, :des => @des, :hom => @hom, :off => @off, :par => @par, :ret => @ret, :eve => @eve, :reg => @reg, :dat => @dat, :rall => @rall))
                   when (@par and @product.partner == true)
                     @p = Product.where('partner = "t"')
                     @hash = Hash[@p.map.with_index.to_a]
                     @i = @hash[@product]
                     @m = @p.count

                     (@i == 0 ? products_show_path(:id => @p[@m - 1].id, :pro => @pro, :par => @par, :des => @des, :hom => @hom, :off => @off, :top => @top, :ret => @ret, :eve => @eve, :reg => @reg, :dat => @dat, :rall => @rall) : products_show_path(:id => @p[@i.to_i - 1].id, :pro => @pro, :par => @par, :des => @des, :hom => @hom, :off => @off, :top => @top, :ret => @ret, :eve => @eve, :reg => @reg, :dat => @dat, :rall => @rall))
                   when @ret
                     @p = Retailer.find(@ret).products
                     @hash = Hash[@p.map.with_index.to_a]
                     @i = @hash[@product]
                     @m = @p.count

                     (@i == 0 ? products_show_path(:id => @p[@m - 1].id, :pro => @pro, :ret => @ret, :des => @des, :hom => @hom, :off => @off, :top => @top, :par => @par, :eve => @eve, :reg => @reg, :dat => @dat, :rall => @rall) : products_show_path(:id => @p[@i.to_i - 1].id, :pro => @pro, :ret => @ret, :des => @des, :hom => @hom, :off => @off, :top => @top, :par => @par, :eve => @eve, :reg => @reg, :dat => @dat, :rall => @rall))
                   when @eve
                     @p = Event.find(@eve).products
                     @hash = Hash[@p.map.with_index.to_a]
                     @i = @hash[@product]
                     @m = @p.count

                     (@i == 0 ? products_show_path(:id => @p[@m - 1].id, :pro => @pro, :eve => @eve, :des => @des, :hom => @hom, :off => @off, :top => @top, :par => @par, :ret => @ret, :reg => @reg, :dat => @dat, :rall => @rall) : products_show_path(:id => @p[@i.to_i - 1].id, :pro => @pro, :eve => @eve, :des => @des, :hom => @hom, :off => @off, :top => @top, :par => @par, :ret => @ret, :reg => @reg, :dat => @dat, :rall => @rall))
                   else
                 end


    @path_up = case
                  when @des
                    designers_show_path(:id => @des, :pro => 0, :des => @des, :hom => @hom, :off => @off, :top => @top, :par => @par, :ret => @ret, :eve => @eve, :reg => @reg, :dat => @dat, :rall => @rall)
                  when (@hom and @product.category == @hom)
                    products_home_by_type_path(:category => @hom, :pro => @pro, :des => @des, :hom => @hom, :off => @off, :top => @top, :par => @par, :ret => @ret, :eve => @eve, :reg => @reg, :dat => @dat, :rall => @rall)
                  when (@off and @product.category == @off)
                    products_office_by_type_path(:category => @off, :pro => @pro, :des => @des, :hom => @hom, :off => @off, :top => @top, :par => @par, :ret => @ret, :eve => @eve, :reg => @reg, :dat => @dat, :rall => @rall)
                  when (@top and @product.top == true)
                    products_top_path
                  when (@par and @product.partner == true)
                    products_by_partners_path
                  when @ret
                    retailers_retailers_products_path(:id => @ret, :pro => @pro, :des => @des, :hom => @hom, :off => @off, :top => @top, :par => @par, :eve => @eve, :reg => @reg, :dat => @dat, :rall => @rall)
                  when @eve
                    events_events_products_path(:id => @eve, :pro => @pro, :des => @des, :hom => @hom, :off => @off, :top => @top, :par => @par, :ret => @ret, :eve => @eve, :reg => @reg, :dat => @dat, :rall => @rall)
                  else
                end

    @path_right = case
                   when @des
                     @p = Designer.find(@des).designed_products
                     hash = Hash[@p.map.with_index.to_a]
                     @i = hash[@product]
                     @m = @p.count

                     (@i == (@m - 1) ? products_show_path(:id => @p[0].id, :pro => @pro, :des => @des, :hom => @hom, :off => @off, :top => @top, :par => @par, :ret => @ret, :eve => @eve, :reg => @reg, :dat => @dat, :rall => @rall) : products_show_path(:id => @p[@i.to_i + 1].id, :pro => @pro, :des => @des, :hom => @hom, :off => @off, :top => @top, :par => @par, :ret => @ret, :eve => @eve, :reg => @reg, :dat => @dat, :rall => @rall))
                   when (@hom and @product.category == @hom)
                     @p = Product.where('category = ?', @hom)
                     hash = Hash[@p.map.with_index.to_a]
                     @i = hash[@product]
                     @m = @p.count

                     (@i == (@m - 1) ? products_show_path(:id => @p[0].id, :pro => @pro, :hom => @hom, :des => @des, :off => @off, :top => @top, :par => @par, :ret => @ret, :eve => @eve, :reg => @reg, :dat => @dat, :rall => @rall) : products_show_path(:id => @p[@i.to_i + 1].id, :pro => @pro, :hom => @hom, :des => @des, :off => @off, :top => @top, :par => @par, :ret => @ret, :eve => @eve, :reg => @reg, :dat => @dat, :rall => @rall))
                   when (@off and @product.category == @off)
                     @p = Product.where('category = ?', @off)
                     hash = Hash[@p.map.with_index.to_a]
                     @i = hash[@product]
                     @m = @p.count

                     (@i == (@m - 1) ? products_show_path(:id => @p[0].id, :pro => @pro, :off => @off, :des => @des, :hom => @hom, :top => @top, :par => @par, :ret => @ret, :eve => @eve, :reg => @reg, :dat => @dat, :rall => @rall) : products_show_path(:id => @p[@i.to_i + 1].id, :pro => @pro, :off => @off, :des => @des, :hom => @hom, :top => @top, :par => @par, :ret => @ret, :eve => @eve, :reg => @reg, :dat => @dat, :rall => @rall))
                   when (@top and @product.top == true)
                     @p = Product.where('top = "t"')
                     hash = Hash[@p.map.with_index.to_a]
                     @i = hash[@product]
                     @m = @p.count

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/products/all_home.html.erb
<% content_for :orientation do %>
    prodotti<span class="orientsep"> -> </span> <%= link_to "prodotti casa", products_all_home_path %>
<% end %>

<% content_for :rightcol do %>
    <h1>Prodotti Casa</h1>
    <div>
        <div class="pageobject">
          <%= link_to products_home_by_type_path(:category => "soggiorno") do %>
              <%= image_tag("soggiorno.jpg", :width => 290, :height => 210) %> <br><span class="imgsubtitle">Soggiorno</span>
          <% end %>
        </div>
          <div class="pageobject">
            <%= link_to products_home_by_type_path(:category => "cucina") do %>
                <%= image_tag("cucina.jpg", :width => 290, :height => 210) %> <br><span class="imgsubtitle">Cucina</span>
            <% end %>
          </div>
          <div class="pageobject">
            <%= link_to products_home_by_type_path(:category => "zonanotte") do %>
                <%= image_tag("zonanotte.jpg", :width => 290, :height => 210) %> <br><span class="imgsubtitle">Zona Notte</span>
            <% end %>
          </div>
          <div class="pageobject">
            <%= link_to products_home_by_type_path(:category => "bagno") do %>
                <%= image_tag("bagno.jpg", :width => 290, :height => 210) %> <br><span class="imgsubtitle">Bagno</span>
            <% end %>
          </div>
    </div>
<% end %>

<% content_for :leftcol do %>
<% end %>

app/views/products/all_office.html.erb
<% content_for :orientation do %>
    prodotti<span class"orientsep"> -> </span> <%= link_to "prodotti ufficio", products_all_office_path %>
<% end %>

<% content_for :rightcol do %>
    <h1>Prodotti ufficio</h1>
    <div>
      <div class="pageobject">
        <%= link_to products_office_by_type_path(:category => "reception") do %>
            <%= image_tag("reception.jpg", :width => 290, :height => 210) %> <br><span class="imgsubtitle">Reception</span>
        <% end %>
      </div>
      <div class="pageobject">
        <%= link_to products_office_by_type_path(:category => "direzionale") do %>
            <%= image_tag("direzionale.jpg", :width => 290, :height => 210) %> <br><span class="imgsubtitle">Direzionale</span>
        <% end %>
      </div>
      <div class="pageobject">
        <%= link_to products_office_by_type_path(:category => "operativita") do %>
            <%= image_tag("operativita.jpg", :width => 290, :height => 210) %> <br><span class="imgsubtitle">Operatività</span>
        <% end %>
      </div>
      <div class="pageobject">
        <%= link_to products_office_by_type_path(:category => "archiviazione") do %>
            <%= image_tag("archiviazione.jpg", :width => 290, :height => 210) %> <br><span class="imgsubtitle">Archiviazione</span>
        <% end %>
      </div>
    </div>
<% end %>

<% content_for :leftcol do %>
<% end %>

app/views/products/by_partners.html.erb
<% content_for :orientation do %>
    prodotti<span class="orientsep"> -> </span><%= link_to "prodotti partners", products_by_partners_path %>
<% end %>

<% content_for :rightcol do %>
<h1>Prodotti dai nostri partner</h1>
<ul>
  <% @partners_prod.each do |product| %>
      <li class="productelem">
        <% if (product.pictures[0]) %>
            <%=link_to image_tag(product.pictures[0].url_image, :alt => product.name, :width => 300), products_show_path(:id => product.id, :par => true)%>
        <% else %>
            <%=link_to image_tag("productdefault.jpg", :alt => product.name, :width => 300), products_show_path(:id => product.id, :par => true)%>
        <% end %>
        <%= link_to product.name, products_show_path(:id => product.id, :par => true), :class => "productname" %>
      </li>
  <% end %>
</ul>
<% end %>

<% content_for :right do %>
<% end %>

app/views/products/home_by_type.html.erb
<% content_for :orientation do %>
    prodotti<span class="orientsep"> -> </span> <%= link_to "prodotti casa", products_all_home_path %><span class="orientsep"> -> </span> <%= link_to @cat, products_home_by_type_path(:category => @cat)%>
<% end %>

<% content_for :rightcol do %>
<h1>Prodotti casa per <%= @cat %></h1>
    <% if @home_prod[0] %>
        <ul>
          <% @home_prod.each do |product| %>
              <li class="productelem">
                <% if (product.pictures[0]) %>
                    <%=link_to image_tag(product.pictures[0].url_image, :alt => product.name, :width => 300), products_show_path(:id => product.id, :hom => @cat)%>
                <% else %>
                    <%=link_to image_tag("productdefault.jpg", :alt => product.name, :width => 300), products_show_path(:id => product.id, :hom => @cat)%>
                <% end %>
                <%= link_to product.name, products_show_path(:id => product.id, :hom => @cat), :class => "productname" %>
              </li>
          <% end %>
        </ul>
    <% else %>
    Nessun prodotto casa per <%= @cat %> trovato.
    <% end %>
<% end %>

<% content_for :leftcol do %>
    <div class="row">
      <%= link_to products_all_home_path do %>
          <%= image_tag("buttonbwd.png", :width => 40, :class => "icon") %><span class="pagesubtitle">Torna a prodotti casa</span>
      <% end %>
    </div>
<% end %>

app/views/products/new_home.html.erb
<% content_for :rightcol do %>
    <h1>Insert a new home Product into the database</h1>



    <%= form_for(@product) do |f| %>
        <% if @product.errors.any? %>
            <div id="error_explanation">
              <h2><%= pluralize(@product.errors.count, "error") %> prohibited this post from being saved:</h2>

              <ul>
                <% @product.errors.full_messages.each do |msg| %>
                    <li><%= msg %></li>
                    <%= @product.name %>
                    <%= @product.partner %>
                    <%= @product.top %>
                <% end %>
              </ul>
            </div>
        <% end %>

        <div class="field">
          <%= f.label :name %><br>
          <%= f.text_field :name %>
        </div>
        <div class="field">
          <%= f.label :description %><br>
          <%= f.text_area :description %>
        </div>
        <div class="field">
          <%= f.label :services %><br>
          <%= f.text_area :services %>
        </div>
        <div class="field"><br>
          <%= f.label :top %>
          <%= f.check_box :top %>
        </div>
        <div class="field"><br>
            <%= f.label :category %>
            <%= f.select :category, ["soggiorno", "bagno", "cucina", "zonanotte"] %>
        </div>
        <div class="actions"><br>
          <%= f.submit %>
        </div>
    <% end %>

<% end %>

<% content_for :leftcol do %>
  <div class="row">
    <%= link_to "Back to Admin page", pages_admin_path %>
  </div>
<% end %>

app/views/products/products_retailers.html.erb
<% content_for :orientation do %>

        <%=link_to @product.name ,products_show_path(:id => @product.id, :pro => @pro, :des => @des, :hom => @product.category, :off => @off, :top => @top, :par => @par, :ret => @ret, :eve => @eve, :reg => @reg, :dat => @dat, :rall => @rall)%> <span class="orientsep"> -> </span> <%= link_to "rivenditori", products_products_retailers_path(:hom => @product.category, :id => @product.id) %>

<% end %>

<% content_for :rightcol do %>
<h1>Puoi trovare <%= @product.name %> nei seguenti rivenditori:</h1>

<ul class="productretailerslist">
<% @product.retailers.each do |retailer| %>
<li><%= link_to retailers_show_path(:id => retailer.id, :pro => @product.id, :des => @des, :hom => @hom, :off => @off, :top => @top, :par => @par, :ret => @ret, :eve => @eve, :reg => @reg, :dat => @dat, :rall => @rall) do %>
      <%= image_tag(retailer.photo_url, :width => 200, :class => "retailerphoto")%> <span class="retailerername"><%=retailer.name+": "+retailer.region %></span>
  <% end %></li>
<% end %>
</ul>
<% end %>

<% content_for :leftcol do %>
    <div class="row">
      <%= link_to products_show_path(:id => @product.id, :pro => @pro, :des => @des, :hom => @product.category, :off => @off, :top => @top, :par => @par, :ret => @ret, :eve => @eve, :reg => @reg, :dat => @dat, :rall => @rall) do %>
          <%= image_tag("buttonbwd.png", :width => 40, :class => "icon") %><span class="pagesubtitle">Torna a</span><span class="gray"><%=@product.name%></span>
      <% end %>
    </div>
<% end %>

app/views/products/show.html.erb
<% content_for :orientation do %>
    <% if(!@ret)%>
        <%if(@des)%>
            <%= link_to "Designers", designers_all_path %><span class="orientsep"> -> </span><%= link_to @desname, designers_show_path(:id => @des)%><span class="orientsep"> -> </span><%= link_to @product.name, products_show_path(:id => @product.id, :des => @des, :pro => @pro, :hom => @hom, :off => @off, :top => @top, :par => @par, :ret => @ret, :eve => @eve, :reg => @reg, :dat => @dat, :rall => @rall) %>

        <%elsif(!@des && @par)%>
            prodotti<span class="orientsep"> -> </span><%= link_to "prodotti partners", products_by_partners_path%><span class="orientsep"> -> </span><%= link_to @product.name, products_show_path(:id => @product.id, :des => @des, :pro => @pro, :hom => @hom, :off => @off, :top => @top, :par => @par, :ret => @ret, :eve => @eve, :reg => @reg, :dat => @dat, :rall => @rall) %>

        <% elsif(@top)%>
            prodotti<span class="orientsep"> -> </span><%= link_to "prodotti top", products_top_path%><span class="orientsep"> -> </span><%= link_to @product.name, "" %>

        <%elsif(@product.home_office) %>
            prodotti<span class="orientsep"> -> </span> <%= link_to "prodotti casa", products_all_home_path %><span class="orientsep"> -> </span> <%= link_to @hom, products_home_by_type_path(:category => @hom)%><span class="orientsep"> -> </span><%= link_to @product.name, products_show_path(:id => @product.id, :des => @des, :pro => @pro, :hom => @hom, :off => @off, :top => @top, :par => @par, :ret => @ret, :eve => @eve, :reg => @reg, :dat => @dat, :rall => @rall) %>

        <%elsif(!@product.home_office) %>
            prodotti<span class="orientsep"> -> </span> <%= link_to "prodotti ufficio", products_all_office_path %><span class="orientsep"> -> </span> <%= link_to @off, products_office_by_type_path(:category => @off)%><span class="orientsep"> -> </span><%= link_to @product.name, products_show_path(:id => @product.id, :des => @des, :pro => @pro, :hom => @hom, :off => @off, :top => @top, :par => @par, :ret => @ret, :eve => @eve, :reg => @reg, :dat => @dat, :rall => @rall) %>

        <% end %>
    <% else %>
        <% link_to @retname, "/retailers/retailers_products/?id="+@ret %>
    <% end %>
<% end %>

<% content_for :rightcol do %>
    <h1 class="productname"><%= @product.name %></h1>
    <h3 class="productdesigner"><% @product.designers.each do |designer| %>
          <%= designer.name+" "+designer.lastname %>
      <% end %>
    </h3>

    <div id="slidercont">
      <% if (@product.pictures[0]) %>
          <% if @product.pictures[1] %>
              <%=image_tag("slider_arrow_left.png", :width => 80, :id => "arrowleft", :class => "sliderarrow")%>
              <%=image_tag("slider_arrow_right.png", :width => 80, :id => "arrowright", :class => "sliderarrow")%>
          <% end %>
          <div id="slider" style="position:absolute;left:0;width:<%=@product.pictures.length*600%>px">
            <% @product.pictures.each do |prodpict| %>
                <div class="sliderobj"><%=image_tag(prodpict.url_image, :height => 230) %></div>
            <% end %>
          </div>
      <% else %>
          <div class="sliderobj"><%=image_tag("productdefault.jpg", :height => 230) %></div>
      <% end %>
    </div>

    <div class="row">
      <%=image_tag("formatbullets.png", :width => 40, :class => "icon")%> <span class="pagesubtitle">Descrizione</span>
    </div>
    <p class="paragraph"><%=@product.description %></p>

    <div class="row">
      <%=image_tag("servizi.png", :width => 40, :class => "icon")%> <span class="pagesubtitle">Servizi</span>
    </div>
    <p class="paragraph"><%=@product.services %></p>

    <div class="row">
      <%=image_tag("pen.png", :width => 40, :class => "icon")%> <span class="pagesubtitle">Designers</span>
    </div>
    <div>
      <% @product.designers.each do |designer| %>
          <div class="designerelem">
            <%= link_to designers_show_path(:id => designer.id, :pro => @product.id, :des => @des, :hom => @hom, :off => @off, :top => @top, :par => @par, :ret => @ret, :eve => @eve, :reg => @reg, :dat => @dat, :rall => @rall) do %>
                <%= image_tag(designer.photo_url, :width => 100, :class => "designerphoto")%> <span class="designername"><%=designer.name+" "+designer.lastname %></span>
            <% end %>
          </div>
      <% end %>
    </div>
    <div class="row">
      <div class="arrowcontainer">
        <% if @path_left %>
            <%=link_to @path_left do%>
                <%= image_tag("arrowleft.png", :width => 60, :class => "leftarrowpage")%>
            <% end %>
        <% end %>
        <% if @path_up %>
            <%=link_to @path_up do%>
                <%= image_tag("arrowup.png", :width => 60, :class => "uparrowpage")%>
            <% end %>
        <% end %>
        <% if @path_right %>
            <%=link_to @path_right do%>
                <%= image_tag("arrowright.png", :width => 60, :class => "rightarrowpage")%>
            <% end %>
        <% end %>
      </div>
    </div>
<% end %>

<% content_for :leftcol do %>
    <div class="row">
      <%= link_to products_products_retailers_path(:id => @product.id, :pro => @pro, :des => @des, :hom => @hom, :off => @off, :top => @top, :par => @par, :ret => @ret, :eve => @eve, :reg => @reg, :dat => @dat, :rall => @rall) do %>
          <%= image_tag("resellersicon.png", :width => 40, :class => "icon") %><span class="pagesubtitle">Rivenditori</span><span class="gray"><%=@product.name%></span>
      <% end %>
    </div>
    <div class="row">
      <%=image_tag("eventsicon.png", :width => 40, :class => "icon")%> <span class="pagesubtitle">Eventi</span><span class="gray"><%=@product.name%></span>
    </div>
    <% if !@product.events[0] %> Nessun evento associato. <% else %>
        <ul class="eventlist">
          <% @product.events.each do |event| %>
              <%= link_to events_show_path(:id => event.id, :pro => @product.id, :des => @des, :hom => @hom, :off => @off, :top => @top, :par => @par, :ret => @ret, :eve => @eve, :reg => @reg, :dat => @dat, :rall => @rall) do%>
                  <li class="eventobject"><p><%=event.date%></p><p>@<%=event.name+","+event.place%></p></li>
              <% end %>
          <% end %>
        </ul>
    <% end %>
<% end %>